<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3lxGBw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3lxGBw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS3lxGBw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS3lxGBw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS3lxGBw\App_KernelDevDebugContainer([
    'container.build_hash' => 'S3lxGBw',
    'container.build_id' => '5dfb69ee',
    'container.build_time' => 1684771598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS3lxGBw');
